/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.93
 * Generated at: 2020-04-01 11:50:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import rl.medicine.utility.AppUtility;
import rl.medicine.utility.AppLogger;
import rl.medicine.model.DataIdModel;
import rl.medicine.dto.MedicineDetailDTO;
import rl.medicine.utility.AppConstant;
import java.util.List;
import java.util.ArrayList;
import java.util.Set;
import java.util.HashMap;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.time.LocalDateTime;
import java.time.ZoneId;

public final class medicine_005fchemical_005fname_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>All Medicine</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".tab {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tleft: 150px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".tab2 {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tleft: 400px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tab3 {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tleft: 600px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");

	final String JSP_TAG = "all_medicine.jsp";

	final List<MedicineDetailDTO> allMedicines = (List<MedicineDetailDTO>) 
			request.getAttribute(AppConstant.ATTRIBUTE_ALL_MEDICINE);
	
 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<h1> <font color=\"black\"><b>All Medicine </b></font></h1><br/>\r\n");

	for(int index = 0; index < allMedicines.size(); index++){
	final MedicineDetailDTO medicineDetailName = allMedicines.get(index);
	final String medicineChemicalName = medicineDetailName.getMedicineChemicalName();
	final MedicineDetailDTO medicineCountDetail = medicineDetailName.getMedicineDetailDTO();
	final Set<String> medicineNames = medicineCountDetail.getMedicineNames();
	String medicineName = "";
	for(String medicineNameData : medicineNames){
		if(medicineName.isEmpty()){
			medicineName = medicineNameData;
		}else{
			medicineName = medicineName+", "+medicineNameData;
		}
	}
 	AppLogger.appDebug(JSP_TAG+" medicineCountDetail "+medicineCountDetail);
	final int totalStrips = medicineCountDetail.getStrip();
	final int totalLeftQuantity = medicineCountDetail.getLeftQuantity();
	final Date minimumExpiryDate =  medicineCountDetail.getMedicineExpiryDate();
	final Date maximumExpiryDate = medicineCountDetail.getMaxExpiryDate();
	final SimpleDateFormat simpleDateFormat = new SimpleDateFormat("MMMMM-yyyy");
	final String minimumExpiryDateString = simpleDateFormat.format(minimumExpiryDate);
	final String maximumExpiryDateString = simpleDateFormat.format(maximumExpiryDate);
	int totalTablets = 0;
	if(medicineName.contains("15")){
		AppLogger.appDebug(JSP_TAG+" medicine Name "+medicineName+" is 15 tab");
		totalTablets = totalStrips * 15;
	}else if(medicineName.contains("6")){
		AppLogger.appDebug(JSP_TAG+" medicine Name "+medicineName+" is 6 tab");
		totalTablets = totalStrips * 6;
	}else{
		totalTablets = totalStrips * 10;
	}
	
	AppLogger.appDebug(JSP_TAG+" total  Tablets : "+totalTablets+", total Quantity : "+medicineCountDetail.getTotalQuantity()+" for chemical name : "+medicineChemicalName);
	totalTablets = medicineCountDetail.getTotalQuantity();
	totalTablets = totalTablets + totalLeftQuantity;
	LocalDateTime today =  LocalDateTime.now();     //Today
  
System.out.println(today);          //2018-07-14
 
 long days = 0l;
 if(medicineName.toLowerCase().contains("serlift")){
 AppLogger.appDebug(JSP_TAG+" Medicine Name : "+medicineName+" is divide by 2 ");
 	days = (long)totalTablets / 2;
 }else{
 	days = totalTablets;
 }
LocalDateTime sameDayNextDateYear = today.plusDays(days);     //2019-07-14
 
//Get Date from LocalDateTime 
//Not recommended. Use when you have no options in legacy code.
Date currentDatePlusOneDay = Date.from(sameDayNextDateYear.atZone(ZoneId.systemDefault()).toInstant());
 
	
	
	String nextTillDate = new String();
	Date dateOfUseFinal = new Date();
	final SimpleDateFormat simpleDateFormatForDay = new SimpleDateFormat("dd-MMMMM-yyyy");
	nextTillDate = simpleDateFormatForDay.format(currentDatePlusOneDay);
	
	
	
      out.write("\r\n");
      out.write("\t<h3><font color = \"dark_red\"><b> ");
      out.print( medicineChemicalName);
      out.write("</b></font></h2> \r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<table name = \"medicine_data\"  border=\"1\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th><font color=\"#EA8D3F\">Medicine Name </font></th>\r\n");
      out.write("\t\t\t\t<th><font color=\"#EA8D3F\">Total Strips </font></th>\r\n");
      out.write("\t\t\t\t<th><font color=\"#EA8D3F\">Left Quantity </font></th>\r\n");
      out.write("\t\t\t\t<th><font color=\"#EA8D3F\">Minimum Expiry Date </font></th>\r\n");
      out.write("\t\t\t\t<th><font color=\"#EA8D3F\">Maximum Expiry Date </font></th>\r\n");
      out.write("\t\t\t\t<th><font color=\"#EA8D3F\">Total Tablet counts </font></th>\r\n");
      out.write("\t\t\t\t<th><font color=\"#EA8D3F\">Next date as dose current from Today </font></th>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t<td><b><font color=\"blue\">");
      out.print( medicineName);
      out.write("</font></b></td>\r\n");
      out.write("\t\t\t<td><b><font color=\"blue\">");
      out.print( totalStrips);
      out.write("</font></b></td>\r\n");
      out.write("\t\t\t<td><b><font color=\"blue\">");
      out.print( totalLeftQuantity);
      out.write("</font></b></td>\r\n");
      out.write("\t\t\t<td><b><font color=\"blue\">");
      out.print( minimumExpiryDateString);
      out.write("</font></b></td>\r\n");
      out.write("\t\t\t<td><b><font color=\"blue\">");
      out.print( maximumExpiryDateString);
      out.write("</font></b></td>\r\n");
      out.write("\t\t\t<td><b><font color=\"blue\">");
      out.print( totalTablets );
      out.write("</font></b></td>\r\n");
      out.write("\t\t\t<td><b><font color=\"blue\">");
      out.print( nextTillDate);
      out.write("</font></b></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<br/>\r\n");
      out.write("\t");
 
	 
	}// end of medicine Name for loop
 
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
